/*! modernizr 3.3.1 (Custom Build) | MIT *
 * http://modernizr.com/download/?-json-svg-setclasses !*/

/*! modernizr 3.3.1 (Custom Build) | MIT *
 * http://modernizr.com/download/?-eventlistener-localstorage-svg-setclasses !*/
!function (e, n, s) { function t(e, n) { return typeof e === n } function o() { var e, n, s, o, a, l, c; for (var f in r) if (r.hasOwnProperty(f)) { if (e = [], n = r[f], n.name && (e.push(n.name.toLowerCase()), n.options && n.options.aliases && n.options.aliases.length)) for (s = 0; s < n.options.aliases.length; s++) e.push(n.options.aliases[s].toLowerCase()); for (o = t(n.fn, "function") ? n.fn() : n.fn, a = 0; a < e.length; a++) l = e[a], c = l.split("."), 1 === c.length ? Modernizr[c[0]] = o : (!Modernizr[c[0]] || Modernizr[c[0]] instanceof Boolean || (Modernizr[c[0]] = new Boolean(Modernizr[c[0]])), Modernizr[c[0]][c[1]] = o), i.push((o ? "" : "no-") + c.join("-")) } } function a(e) { var n = c.className, s = Modernizr._config.classPrefix || ""; if (f && (n = n.baseVal), Modernizr._config.enableJSClass) { var t = new RegExp("(^|\\s)" + s + "no-js(\\s|$)"); n = n.replace(t, "$1" + s + "js$2") } Modernizr._config.enableClasses && (n += " " + s + e.join(" " + s), f ? c.className.baseVal = n : c.className = n) } var i = [], r = [], l = { _version: "3.3.1", _config: { classPrefix: "", enableClasses: !0, enableJSClass: !0, usePrefixes: !0 }, _q: [], on: function (e, n) { var s = this; setTimeout(function () { n(s[e]) }, 0) }, addTest: function (e, n, s) { r.push({ name: e, fn: n, options: s }) }, addAsyncTest: function (e) { r.push({ name: null, fn: e }) } }, Modernizr = function () { }; Modernizr.prototype = l, Modernizr = new Modernizr, Modernizr.addTest("eventlistener", "addEventListener" in e), Modernizr.addTest("svg", !!n.createElementNS && !!n.createElementNS("http://www.w3.org/2000/svg", "svg").createSVGRect); var c = n.documentElement, f = "svg" === c.nodeName.toLowerCase(); Modernizr.addTest("localstorage", function () { var e = "modernizr"; try { return localStorage.setItem(e, e), localStorage.removeItem(e), !0 } catch (n) { return !1 } }), o(), a(i), delete l.addTest, delete l.addAsyncTest; for (var d = 0; d < Modernizr._q.length; d++) Modernizr._q[d](); e.Modernizr = Modernizr }(window, document);

function browserSupported() {
    return Modernizr.svg && Modernizr.localstorage && Modernizr.eventlistener;
}
